Upgrade @openzeppelin/contracts-upgradeable to 4.8.0 (#425)
* Refactor: upgrade @openzeppelin/contract-upgradeable to 4.8.0

MarketplaceV3 was deployed using 4.6.0 (or newer), so OZ dependency can't be downgraded (due to changed storage layouts, see https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.8.0/contracts/proxy/utils/Initializable.sol#L62 vs https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/v4.5.2/contracts/proxy/utils/Initializable.sol#L39). Best bet is to keep moving up the versions and hope OZ won't hose us.

* build: deployed new version of Marketplace to Polygon

* refactor: revert changes to old files (to accommodate new OZ version), instead use NPM alias to 4.4.2

* refactor: use ERC2771ContextUpgradeable from 4.8.0 instead of 4.4.2/Users/jtakalai/Documents/workspace/network-contracts/packages/hub-contracts/contracts/ProjectRegistry/ProjectRegistry.sol

* refactor: move flattened file outside the contracts source dir hierarchy

* fix: add decorator to silence an error

The error is kind of perplexing, given that the constructor is required by ERC2771ContextUpgradeable that itself defines a constructor with an argument:
```
 Error: Contract `contracts/ProjectRegistry/ProjectRegistry.sol:ProjectRegistry` is not upgrade safe

contracts/ProjectRegistry/ProjectRegistry.sol:53: Contract `ProjectRegistry` has a constructor
    Define an initializer instead
    https://zpl.in/upgrades/error-001
```