ETH-501 add operator-client package (#523)
* feat: ETH-501 add operator-client package

* fixed build, test still broken

* WIP setting up test with operator contract in local dev-env

* WIP debugging operator-client integration in local dev env

* manual test of OperatorClient for staked and unstaked events works, testcase with predeployed contracts in chain still has some bug

* test: deploy Operator/Sponsorship contract

adapted from network-contracts test helpers

* test: fix compile errors

* fix: compile errors

* WIP test still failing after refactor with Juuso

* build: remove unused packages from build

* build: tsconfig cleanup

* test: fix OperatorClient test and deployment of contracts

* build: revert unrelated change

* test: cleanup

* WIP query thegraph

* build: revert package-lock.json

can't reproduce the CI problems:
```
Error: Cannot find module '@chainsafe/as-sha256'
Error: Cannot find module '@nomicfoundation/hardhat-chai-matchers'
```

* build: set node version to 18.16.0

* build: debugging

* graphQL connection and query working, test at the moment still needs manually set up contracts to work

* Revert "build: debugging"

This reverts commit fc4b79249fcb7cc318b217c279a303b48b2ba211.

* moved from ts-mocha to ts-jest, import actually correct version of node-fetch, integrated Logger from streamr utils

* fix jest config name

* fix graphql result parsing, getAllstreams als returns ones from eventhandling

* build: add missing dependencies

...that ARE in the dependency chain but mysteriously dropped by `npm i`

* test: add --runInBand to jest

* build: add missing dependencies

chat-contracts lint needed them

* fix: lint

* build: consistent npm cache keys

* test: types in OperatorClient tests

* build: add OperatorClient integration-test

* build: add missing dependency

explicitly into package.json though it should already exist as transitive dependency

* release(network-contracts, config): 2.6.0

* release(network-contracts): 2.6.1

added missing solidity files

* build: replace @streamr-contracts/network-contracts -> @streamr/network-contracts everywhere

that's the NPM package name, no reason to keep another name "internally"

* release(operator-client): 2.6.1

* build: fix package name

* build: fix JSON

* build: add clean step before build

sometimes `hardhat compile` seems to fail to generate artifact JSONs in Github Actions. Mysterious.

* fix: fixed bug with getAllStakedStreams; added more Tests

* Revert "fix: fixed bug with getAllStakedStreams; added more Tests"

This reverts commit d0747382a2d4c83937056a5766db180e6b63efe6.

* build: defensive programming, ensure build step

CI is getting the error of `hardhat compile` not having produced artifacts. Just ask it to do it again.

Error in CI: `jq: error: Could not open file ../network-contracts/artifacts/contracts/NodeRegistry/NodeRegistry.sol/NodeRegistry.json: No such file or directory`

* build: update package-lock.json

this seems to make integration-test in CI pass (tested in another branch)

* build: attempt to force `hardhat compile` to product artifacts, without invoking npm

there could be a race condition between npm tasks... impossible to say. Log:
```
> @streamr/network-contracts@2.6.1 build
> npm run clean && hardhat compile && rm -rf dist && tsc -p tsconfig.build.json

> @streamr/network-contracts@2.6.1 clean
> rm -rf artifacts dist cache coverage typechain deployments .openzeppelin/unknown-31337.json

You have both ethereum-waffle and @nomicfoundation/hardhat-chai-matchers installed. They don't work correctly together, so please make sure you only use one.

We recommend you migrate to @nomicfoundation/hardhat-chai-matchers. Learn how to do it here: https://hardhat.org/migrate-from-waffle
Downloading compiler 0.8.13
Error: src/exports.ts(1,66): error TS2307: Cannot find module '../artifacts/contracts/OperatorTokenomics/Operator.sol/Operator.json' or its corresponding type declarations.
```

* build: Try with older node version

suggested by https://github.com/NomicFoundation/hardhat/issues/3877

---------

Co-authored-by: Christoph-Samuel Pitter <christoph-samuel.pitter@streamr.network>