fix: add decorator to silence an error
The error is kind of perplexing, given that the constructor is required by ERC2771ContextUpgradeable that itself defines a constructor with an argument:
```
 Error: Contract `contracts/ProjectRegistry/ProjectRegistry.sol:ProjectRegistry` is not upgrade safe

contracts/ProjectRegistry/ProjectRegistry.sol:53: Contract `ProjectRegistry` has a constructor
    Define an initializer instead
    https://zpl.in/upgrades/error-001
```