ETH-663: check stream exists when deploying Sponsorship (#703)
* fix: ETH-663 check if stream exists

the check was only on one code path of two, move to common code path

(cherry picked from commit 6a8b679c3d92c7ffb71afdedebda9927b2c007a6)

* test: add test for the fix

also, some cleanup

Tested manually without the fix, got the expected error:
```
  1) SponsorshipFactory
       will NOT create a Sponsorship using transferAndCall if the stream does not exist:
     AssertionError: Expected transaction to be reverted with custom error 'StreamNotFound', but it didn't revert
```