test: add test for the fix
also, some cleanup

Tested manually without the fix, got the expected error:
```
  1) SponsorshipFactory
       will NOT create a Sponsorship using transferAndCall if the stream does not exist:
     AssertionError: Expected transaction to be reverted with custom error 'StreamNotFound', but it didn't revert
```