Eth 462 pool subgraph (#487)
* added tatum contracts, fixed running of tests, added deployment script for tatum contracs

* changed schema, rough draft of linking up bountyfactory

* changed schema, rough draft of linking up bountyfactory

* added script to create new bounty, join bounty

* updated contracts and assemblyscript; subgraph sucessfully catching events from deployed bounties; added different sponsoring methods in interaction script;

* more fields in stake and bounty entity are filled

* updated contracts to latest version from 168 branch

* tatum subgraph package is building contrancts on its own, no more copy-pasting artifacts; fixed docker image creation for subgraph deployment container

* Latest contracts (#286)

* fix: corner cases with money running out exactly when something else happens

* ci: run tests for all PRs

* fix: yaml syntax

* build: get solhint config from ETH-168 branch

* fix: make lint happy

* feat: simplifications in StakeWeightedAllocationPolicy

onStakeIncrease happens now BEFORE the unallocatedFunds is increased

* doc: added comments

later if we decide to make modules non-resettable, those updates can be removed

* DefaultLeavePolicy (#301)

* feat: DefaultLeavePolicy: slashing-free leaving after given period

* fix: make test pass

if precisely on the limit, let it be penalty-free leaving...

* Atomic setup (#302)

* WIP atomic setup and adapt tests

* continue to adapt tests to atomic setup

* wierd arithmetic rounding errors in allocpolicy test

* added leavepolicy options to atomic setup

* adapted rest of tests, cleaning up

* fix lint

* rebase to dev

* WIP atomic setup and fund working half

* atomic setup with funding working, added test

* cleanup

* code review cleanups

* Trusted policy list (#304)

* feature that only trusted policies can be set in the bounties, only admin can edit trusted list with pilices in bountyfactory

* added tests for removing policies and for trust-check on pilicies

* code review cleanup

* ETH-275 only allocate when enough brokers (#303)

* feat: merge from branch on top of old develop branch

* feat: ETH-275

maybe more tests for that feature...

* refactor: localData

* Fix: don't show allocation when bounty not running

* test: minBrokerCount must be at least 1

TODO: add require > 0 to factory contract

* Require minBrokerCount > 0 (#305)

* feat: merge from branch on top of old develop branch

* feat: ETH-275

maybe more tests for that feature...

* refactor: localData

* Fix: don't show allocation when bounty not running

* test: minBrokerCount must be at least 1

TODO: add require > 0 to factory contract

* feat: require minBrokerCount > 0

* fix: lint

* removed two "only" and thus enabling all tests

Co-authored-by: Christoph-Samuel Pitter <christoph-samuel.pitter@streamr.network>

* test: small cleanups (#308)

avoiding explicit types ;) esp the <> syntax

* ETH-242: AdminKickPolicy (#311)

* refactor: separate isAdmin and adminOnly for reuse

* feat: commented out unneeded functions, added a comment

* feat: AdminKickPolicy implementation

* test: StreamRegistry tests need fixing

probably some BigNumber issues

* build: update typescript version

I was getting https://stackoverflow.com/questions/72488958/false-expression-non-string-value-passed-to-ts-resolvetypereferencedirective, and update did make it go away

* cleanup: renamings

* refactor: isAdmin function

same as in Bounty

* refactor: BountyFactory takes an array of policies

also pulled deployBountyContract out of the test files where it was used

* build: update package-lock.json

* build: revert package.json updates

this may have caused the following error:
```
Object literal may only specify known properties, and 'namedAccounts' does not exist in type 'HardhatUserConfig'
```

* test: revert skip tests

apparently it was the upgrade of hardhat minor version that broke bignumber comparisons

* build: comment out namedAccounts

it's a hardhat-deploy feature, but we're not using hardhat-deploy...

* cleanup: logging, remove unused member

* feat: added Bounty admin role separate from defaultAdmin

default admin will be the BountyFactory that sets up the modules; normal admin(s) can't change modules, only kick members if AdminKickPolicy is set

* feat: add getter

* fix: wrong order of arguments

* test: move deployBountyContract into utils

* test: AdminKickPolicy

* test: OpenZeppelin standard error message

I'm using the AccessControl feature (modifier onlyRole) instead of writing our own, see https://github.com/OpenZeppelin/openzeppelin-contracts-upgradeable/blob/master/contracts/access/AccessControlUpgradeable.sol#L75

* test: skip logging

* test: lint

* Tatum subgraph (#314)

* adapted subgraph to new bounty deployment format

* add total stake to bounty entity, fixed some calculation

* refactored events, debugging, still showing some wrong values

* fixed bug with one event missing, clean up

* fix lint

* fix: remove merge hazard

* refactor: memberCount -> brokerCount

* refactor: inline variable

Co-authored-by: Juuso Takalainen <juuso@streamr.network>

* PR review fixes to Bounty (#315)

* cleanup: comments

also removed out-commented stuff

* refactor: replace "withdrawn tokens" tracking with zeroing on withdraw

now getAllocation will return zero after withdraw, and also what you would get if you would withdraw now. TODO: more tests!

* refactor: uint -> uint32 for "small numbers"

this MIGHT cause them to be packed better, esp in ERC677.transferAndCall data argument

* fix: test

* build: remove npm caching

Getting this error:
```
Run actions/setup-node@v3
Resolved .nvmrc as 16.14.0
Attempting to download 16.14.0...
Acquiring 16.14.0 - x64 from https://github.com/actions/node-versions/releases/download/16.14.0-1816613615/node-16.14.0-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/c7161c5f-7404-4552-baaf-425379e02b18 -f /home/runner/work/_temp/73331287-63e0-48bf-8328-4fc9a6075534
Adding to the cache ...
Done
/opt/hostedtoolcache/node/16.14.0/x64/bin/npm config get cache
/home/runner/.npm
Error: getCacheEntry failed: Cache service responded with 503
```

* refactor: transferAndCall, remove unused import

* ETH-290: BrokerPool contract (#317)

* fix: lint

* feat: BrokerPool contract and a basic happy path test

* cleanup: remove console.log

* fix: remove function stub

add later if needed

* refactor: commented out unallocatedWei

tracking it seems pointless at this point; after all, it's supposed to at all times be same as the current token balance

* refactor: allow additional staking

* Eth 272 tatum subgraph to dev env (#332)

* add bountyfactory to deployment script for preloading chains

* everything works with predeployed tatum contracts (linked to LINK token)

* tatum scripts are using config package now

* build: remove timestamps from log file

* doc: add comment

Co-authored-by: Juuso Takalainen <juuso@streamr.network>

* added brokerpoolfactory, changed test so that pool is deployed and initialised through factory

* added configurable pooljoin policy, cleaned up tatum contracts locations and linking

* 3 policy types and implementation stubs, all being initialized with config parameters

* Pool is ERC20 token, possibility for compounding curve

* dynamic calculation of pooltoken exchangerate based on poolvalue, with edgecases

* brokers earnings percentage; more tests from szenario doc; partial withdrawing with start for withdraw queue (WIP)

* queue WIP

* WIP
queue is based on pooltokens, not data; fixed some logic and tests with the payout of the queued amounts;
added tests for queue, refactored queuepayout logic, fixed some bugs

* fix partial payout of queue place + deferred payout of queue place

* for calculating poolvalue: refactor: always call all bounties for stake and allocation, allocation is taken into account without brokers share

* small bugfix in a viewfunction, added test for that function

* WIP forced broker stake

* WIP correctly deduct amount of data to divert to brokers stake from his winnings when his stake is below the maintenance margin

* brokers automatic forced stake implemented and tested

* WIP forced withdraw feature

* WIP reduce stake in bounty

* WIP bounty reduce stake

* bounty reduce stake feature and tests work but rounding issue persists

* feat: added reduce stake feature on bounty + tests, added force unstake example scenario test to pool

* WIP loop attack mitigation

* loop attack mitigation plus test

* test to measure gasusage with many bounties

* doc: add a note salvaged from a dead-end branch

* WIP approximate poolvalue

* refactor accesscontrol

* WIP approx poolvalue

* poolvalue update of bounty workflow test

* fixed tests with approx poolvalue

* punish broker not updating poolvalue feature + test

* slashing without action of broker (bountyadmin for now), slash listener in pool and test

* merge from master with switch to harthat-toolbox, fixed tests

* Added StreamrConstats contract and Bountyleavepolicy is using it with checking the global max min join time before slashing. Added test for that case

* added more global constants to its own contract and linked them in pool and poolfactory

* ETH-288: remove State from Bounty (#443)

* ETH-288: clean up tests, remove State from Bounty

* build: run a contract test file from vscode

* fix: whitespace

* fix: cleanup

* test: remove getState

* WIP update/repair bounty deploymentscripts; add pool deployment and configuration scripts; add pool subgraph

* intermediates addresses from scripts are saved in local file and reused in subsequent scripts

* deploymentscript that configures and sets up the poolfactory in local dev env

* scripts to deploy new pool updated

* renamed tatum subgraph package

* link subgraph to tatum contract artifacts from neighbour package

* poolfactory and pool is being indexed, entities are created, linkin is WIP

* investment -> pool -> stake -> bounty is all indexed and linked correctly and queryable from every direction

* reverten folder refactor

* repair indexing of bounty and pool with new Eventnames; remove old package; fix naming of delegator;

* WIP flag in tatum subgraph

* feat: flag entities are being indexed by tatum subgraph

* cleanup

* lint; re-add renamings from master

* fix package-lock issue

* fix package-lock issue 2nd attempt

* attempt to fix CI with package lock generated on arm machine

* attempt to fix dependencies in CI

---------

Co-authored-by: jtakalai <juuso@streamr.network>