PR review fixes to Bounty (#315)
* cleanup: comments

also removed out-commented stuff

* refactor: replace "withdrawn tokens" tracking with zeroing on withdraw

now getAllocation will return zero after withdraw, and also what you would get if you would withdraw now. TODO: more tests!

* refactor: uint -> uint32 for "small numbers"

this MIGHT cause them to be packed better, esp in ERC677.transferAndCall data argument

* fix: test

* build: remove npm caching

Getting this error:
```
Run actions/setup-node@v3
Resolved .nvmrc as 16.14.0
Attempting to download 16.14.0...
Acquiring 16.14.0 - x64 from https://github.com/actions/node-versions/releases/download/16.14.0-1816613615/node-16.14.0-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/c7161c5f-7404-4552-baaf-425379e02b18 -f /home/runner/work/_temp/73331287-63e0-48bf-8328-4fc9a6075534
Adding to the cache ...
Done
/opt/hostedtoolcache/node/16.14.0/x64/bin/npm config get cache
/home/runner/.npm
Error: getCacheEntry failed: Cache service responded with 503
```