fix(network-subgraphs): Build `hub-contracts` (#1017)
Added missing build step to `copyAbisFromContractsPackage.sh`.

The script builds the contracts in `network-contracts` subpackage, but
doesn't build the contracts in the `hub-contracts` subpackage. It should
clearly build both, as it tries to copy the generated hub-contract files
at lines 19-21.

## Error

The `copyAbisFromContractsPackage.sh` is a utility script used by
`build.sh`

If `./build.sh` was run on a clean repository (e.g. after `npm run
clean`), it doesn't have built hub contracts available. It errored like
this:
```
Error: Error in subgraph.yaml:

  Path: dataSources > 4 > mapping > abis > 0 > file
  File does not exist: abis/MarketplaceV4.json

  Path: dataSources > 5 > mapping > abis > 0 > file
  File does not exist: abis/ProjectStakingV1.json
```