Undelegation queue cleanups (#510)
* refactor: queueDataPayout -> undelegate

* refactor: remove public unstake/reduceStakeTo "without paying the queue" functions

* fix: test

weird update requirement I think....

* feat: revert removing "withoutQueue" functions, remove maxIterations arguments from "normal flow" functions, complete an unfinished slow-testcase

the withoutQueue functions aren't problematic like I previously though, since broker can't rebalance while there is queue. It's specifically prevented in stake().

There still needs to be mechanisms for the broker to deal with queue spam; and since broker can't gain from queue after all, it's fine to give the broker more tools (that don't pay the queue).

* build: removed linting temporarily from chat-contracts (solhint crash)

Added resuming linting to ETH-435

Error I'm getting:
```
network-contracts/packages/chat-contracts/node_modules/solhint/lib/index.js:40
      throw e
      ^

TypeError: Cannot set properties of undefined (setting 'stopState')
    at ATNDeserializer3.deserialize (network-contracts/node_modules/@solidity-parser/parser/dist/index.cjs.js:11686:57)
    at Function.get _ATN [as _ATN] (network-contracts/node_modules/@solidity-parser/parser/dist/index.cjs.js:25139:75)
    at new _SolidityLexer (network-contracts/node_modules/@solidity-parser/parser/dist/index.cjs.js:25120:82)
    at Object.parse (network-contracts/node_modules/@solidity-parser/parser/dist/index.cjs.js:36953:17)
    at parseInput (network-contracts/packages/chat-contracts/node_modules/solhint/lib/index.js:17:19)
    at processStr (network-contracts/packages/chat-contracts/node_modules/solhint/lib/index.js:26:11)
    at processFile (network-contracts/packages/chat-contracts/node_modules/solhint/lib/index.js:55:18)
    at network-contracts/packages/chat-contracts/node_modules/solhint/lib/index.js:67:31
    at Array.map (<anonymous>)
    at Object.processPath (network-contracts/packages/chat-contracts/node_modules/solhint/lib/index.js:67:16)
```

sometimes other errors too; from files that compile just fine.

* build: revert removing solhint

* test: fix

* build: revert package-lock.json

* refactor: remove lookup for queue

it's a view function meant for EOA convenience, so gas cost isn't so important. Smart contracts would benefit from the lookup in extreme cases where queue is long, maybe consider it later if smart contracts need it.