ETH-717: added minimum undelegation seconds to StreamrConfig (#788)
* feat: added minimum undelegation seconds to StreamrConfig

* test: add test that transfer is also prevented

make the smart contract change more minimal

* doc: improved comments in test

* feat: add earliestUndelegationTimestamp to Delegation entity

* build: leave ENS sync script out for now, since there's a network problem in the image

* test: add waiting to docker smoke test

received in CI:
```
 Error: GraphQL query failed: ["Store error: query execution failed: Subgraph `QmTBunfA47MvZeaC7acw2RhWcAcfsUXKTkTRb9Z8HgCZov` has not started syncing yet. Wait for it to ingest a few blocks before querying it"]
```

* test: add timeout

* feat: add block explorer urls to config

often useful!

* fix: added field must be last

otherwise upgrading won't work

* doc: add TODO

added ticket ETH-732

* build: add date to scripts

they're our "migrations"

* WIP: streamConfig setter script

* build: cherry-pick scripts from eth-723-ens-sync-script-update-2 branch

for the prettyPrint utils mostly

* feat: rename upgraded StreamrConfig to StreamrConfigV1_1

also deployment scripts

* doc: add roll-back code just in case (commented out)

* test: use the new StreamrConfig

TODO: try to make them all use the one from exports.ts? Not an option with Hardhat I suppose.

* test: StreamrConfig upgradeability tests

* fix: add missing initializer